name: 测试 Actions

on:
  push:
    branches:
      - dev


jobs:
  check-update:
    name: 检查微信读书核心js是否有更新
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest
    outputs:
      needUpgrade: ${{ steps.step3.outputs.exists }}

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: yarn

      - name: 检查微信读书是否更新
        id: step3
        run: | 
          node ./scripts/weread/check-update.js
          test -e ./scripts/weread/tmp/url && echo "exists=true" >> "$GITHUB_OUTPUT" || echo "exists=false" >> "$GITHUB_OUTPUT"

  build:
    name: 打包发布
    needs: check-update
    runs-on: ubuntu-latest
    if: needs.check-update.outputs.needUpgrade == 'true'

    steps:
      - name: 打印job结果
        run: |
          echo "job result: ${{ toJSON(needs.check-update.outputs) }}"

      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: yarn

      - name: 执行构建
        id: build
        run: |
          node ./scripts/weread/check-update.js
          node ./scripts/weread/patch.js
          node ./scripts/weread/build.js
          echo "version=v$(jq -r .version latest.json)" >> "$GITHUB_OUTPUT"

      - name: 输出构建结果
        run: |
          echo "build result: ${{ toJSON(steps.build.outputs) }}"
